# Generated by Django 5.1.6 on 2025-03-08 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('copias', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo_sala', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Posse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyguard.chave')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chave',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyguard.sala'),
        ),
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo', models.TextField()),
                ('data_retirada', models.DateTimeField()),
                ('data_devolucao', models.DateTimeField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyguard.sala')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoPosseChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo_solicitacao', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('data_solicitacao', models.DateTimeField()),
                ('telefone', models.CharField(max_length=15)),
                ('autorizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyguard.autorizacao')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyguard.sala')),
            ],
        ),
        migrations.CreateModel(
            name='StatusGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico_modificacoes', models.JSONField(default=list)),
                ('autorizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyguard.autorizacao')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyguard.chave')),
                ('posse_chaves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyguard.posse')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyguard.sala')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
