# Generated by Django 5.1.6 on 2025-02-12 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyguard.sala')),
            ],
        ),
        migrations.CreateModel(
            name='StatusGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponivel', models.BooleanField(default=True)),
                ('chave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='keyguard.chave')),
            ],
        ),
        migrations.CreateModel(
            name='Posse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyguard.chave')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyguard.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_autorizacao', models.DateTimeField(auto_now_add=True)),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyguard.chave')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyguard.usuario')),
            ],
        ),
    ]
