# Generated by Django 5.1.6 on 2025-03-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyguard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='telefone',
            field=models.CharField(blank=True, default='Não informado', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='autorizacao',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autorizacao',
            name='data_retirada',
            field=models.DateField(),
        ),
    ]
