# Generated by Django 5.1.6 on 2025-03-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyguard', '0002_autorizacao_email_autorizacao_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacao',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autorizacao',
            name='telefone',
            field=models.CharField(default='000-000-0000', max_length=15),
            preserve_default=False,
        ),
    ]
